<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { AlertTriangle, LoaderCircle, Trash2, X } from '@lucide/vue'
import { deleteAdminUser } from '@/api/admin/users'
import type { AdminUser } from '@/api/admin/types'

const props=defineProps<{user:AdminUser|null}>();const emit=defineEmits<{close:[];deleted:[id:number]}>();const identity=ref('');const deleting=ref(false);const error=ref('');const confirmed=computed(()=>Boolean(props.user)&&(identity.value===props.user?.username||identity.value===props.user?.email));watch(()=>props.user,()=>{identity.value='';error.value=''})
async function remove(){if(!props.user||!confirmed.value)return;deleting.value=true;try{await deleteAdminUser(props.user.id);emit('deleted',props.user.id);emit('close')}catch(caught){error.value=caught instanceof Error&&caught.message?caught.message:'删除失败'}finally{deleting.value=false}}
</script>
<template><Transition name="fade"><div v-if="user" class="backdrop" @mousedown.self="emit('close')"><section class="dialog"><header><span><AlertTriangle :size="20" /></span><div><h2>删除用户</h2><p>此操作会停用并移除用户访问权限</p></div><button type="button" @click="emit('close')"><X :size="18" /></button></header><div class="body"><p>请输入用户名 <strong>{{ user.username }}</strong> 或邮箱 <strong>{{ user.email }}</strong> 以确认删除。</p><input v-model="identity" data-testid="delete-user-identity" autocomplete="off" /><span v-if="error" class="error">{{ error }}</span></div><footer><button type="button" class="secondary" @click="emit('close')">取消</button><button type="button" data-testid="confirm-delete-user" :disabled="!confirmed||deleting" @click="remove"><LoaderCircle v-if="deleting" :size="16" class="spinning" /><Trash2 v-else :size="16" />确认删除</button></footer></section></div></Transition></template>
<style scoped>.backdrop{position:fixed;z-index:110;inset:0;display:grid;padding:24px;background:rgba(28,39,56,.28);backdrop-filter:blur(12px);place-items:center}.dialog{width:min(480px,100%);background:white;border:1px solid rgba(255,255,255,.9);border-radius:10px;box-shadow:0 28px 72px rgba(27,42,64,.28)}header{display:grid;grid-template-columns:42px 1fr 32px;align-items:center;gap:10px;padding:20px}header>span{display:grid;width:40px;height:40px;background:#fff0ed;border-radius:9px;color:#b34839;place-items:center}h2{margin:0;font-size:18px}header p{margin:3px 0 0;color:var(--text-tertiary);font-size:12px}header button{border:0;background:transparent;color:var(--text-tertiary);cursor:pointer}.body{padding:0 20px 18px}.body p{margin:0 0 11px;color:var(--text-secondary);font-size:13px;line-height:1.6}.body input{width:100%;height:40px;padding:0 11px;border:1px solid #e1aaa1;border-radius:7px;outline:0}.error{display:block;margin-top:7px;color:#b34839;font-size:12px}footer{display:flex;justify-content:flex-end;gap:9px;padding:14px 20px;border-top:1px solid var(--border-subtle)}footer button{display:flex;height:36px;align-items:center;gap:7px;padding:0 13px;border:0;border-radius:7px;background:#ba4d3c;color:white;cursor:pointer}.secondary{background:var(--bg-base);border:1px solid var(--border-subtle);color:var(--text-secondary)}button:disabled{cursor:default;opacity:.45}.spinning{animation:spin .75s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.fade-enter-active,.fade-leave-active{transition:opacity 180ms}.fade-enter-from,.fade-leave-to{opacity:0}</style>
